// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnQVgXRLN9tJ_HVqnJxIaNe3iSn1r83rQ',
    appId: '1:125066649245:web:ee47f0e2b4bbf892f77e74',
    messagingSenderId: '125066649245',
    projectId: 'hocam-bot',
    authDomain: 'hocam-bot.firebaseapp.com',
    storageBucket: 'hocam-bot.appspot.com',
    measurementId: 'G-QE5WF25X5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9x1ghuYrV5VQ7EtQGFM_EyHBFZAKvjPQ',
    appId: '1:125066649245:android:adaa010df1e70d0af77e74',
    messagingSenderId: '125066649245',
    projectId: 'hocam-bot',
    storageBucket: 'hocam-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVYE4OqC9rS6fO7PubTrQHI0CDQOGzU8',
    appId: '1:125066649245:ios:5bd1e2a7764691c8f77e74',
    messagingSenderId: '125066649245',
    projectId: 'hocam-bot',
    storageBucket: 'hocam-bot.appspot.com',
    iosBundleId: 'com.example.flutterChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVYE4OqC9rS6fO7PubTrQHI0CDQOGzU8',
    appId: '1:125066649245:ios:e6f84b648f13d1b2f77e74',
    messagingSenderId: '125066649245',
    projectId: 'hocam-bot',
    storageBucket: 'hocam-bot.appspot.com',
    iosBundleId: 'com.example.flutterChatbot.RunnerTests',
  );
}
